# -*- coding: utf-8 -*-
"""Lab3-LucasDeLimaDaSilva-NotebookDadosGeo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jVMvW6R95iTFsei3XjQfrRv4gYLlHIo
"""

!pip install pandas numpy matplotlib seaborn

import pandas as pd
import geopandas as gpd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dataset = pd.read_csv('/content/ukraine-russia-refugees-2024.csv')
df_refugiados = dataset[['Country', 'Number of Refugees (15/01/2024)']]
df_refugiados.columns = ['country', 'refugees']

world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))

world = world.rename(columns={'name': 'country'})

df_refugiados['country'] = df_refugiados['country'].str.strip()

world = world.merge(df_refugiados, on='country', how='left')

world['refugees'] = world['refugees'].fillna(0)
world['log_refugees'] = np.log1p(world['refugees'])

fig, ax = plt.subplots(1, 1, figsize=(12, 8))

minx, maxx = -30, 60
miny, maxy = 30, 85
ax.set_xlim(minx, maxx)
ax.set_ylim(miny, maxy)

world.boundary.plot(ax=ax, linewidth=1)

world.plot(column='log_refugees', ax=ax, legend=True,
           legend_kwds={'label': "Número de Refugiados (Escala Logarítmica)",
                        'orientation': "vertical", 'shrink': 0.6},
           cmap='OrRd', edgecolor='black', linewidth=0.5)

ax.set_title('Distribuição dos Refugiados da Guerra da Ucrânia (jan/2024)', fontsize=15)

plt.tight_layout()
plt.show()